create table monitored_account (
	id           bigint generated by default as identity primary key,
	username     varchar(64) not null unique,
	last_sync_at timestamp with time zone,
	created_at   timestamp with time zone not null
);

-- Current snapshot of followers (FOLLOWER) and followed users (FOLLOWING) of each account
create table instagram_connection (
	id         bigint generated by default as identity primary key,
	account_id bigint       not null references monitored_account (id) on delete cascade,
	direction  varchar(16)  not null,
	user_pk    varchar(32)  not null,
	username   varchar(64)  not null,
	full_name  varchar(255),
	since      timestamp with time zone not null,
	constraint uq_instagram_connection unique (account_id, direction, user_pk)
);

-- History of changes detected between two syncs
create table connection_event (
	id          bigint generated by default as identity primary key,
	account_id  bigint       not null references monitored_account (id) on delete cascade,
	direction   varchar(16)  not null,
	type        varchar(16)  not null,
	user_pk     varchar(32)  not null,
	username    varchar(64)  not null,
	full_name   varchar(255),
	occurred_at timestamp with time zone not null
);

create index ix_connection_event_account on connection_event (account_id, occurred_at);

-- Instagram web session reused between runs, to avoid a fresh login every day
create table instagram_session (
	username   varchar(64)  primary key,
	session_id varchar(512) not null,
	csrf_token varchar(256) not null,
	updated_at timestamp with time zone not null
);
